### ISSUE TITLE
Garage door shows as opening even though it is closed

### ISSUE THREAD

**Issue by Conanap** [bwp91/homebridge-meross#282]
**Describe Your Problem:**
Hello! Whenever the garage door opens or closes, the status on the home app shows `opening` for anywhere from a few minutes to a few hours. The meross app shows `closed` as well as the homebridge UI. I've included a portion of the log while the home app shows it as `opening`. I'm not 100% sure this plugin would be the problem, but I thought I'd check here first as none of my other items (eg August lock) seem to have this problem.

**Logs:**
```
[5/26/2021, 10:29:58 PM] [Meross] MSG100 - Reading 192.168.2.53/status
[5/26/2021, 10:29:58 PM] [Meross] MSG100 - Reading 192.168.2.53/status
[5/26/2021, 10:29:58 PM] [Meross] MSG100 Garage door refreshStatus - {"header":{"messageId":"redacted","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"/appliance/redacted/publish","timestamp":redacted,"timestampMs":390,"sign":"redacted"},"payload":{"all":{"system":{"hardware":{"type":"msg100","subType":"us","version":"3.5.0","chipType":"mt7682","uuid":"redacted","macAddress":"redacted"},"firmware":{"version":"3.1.15","compileTime":"2020/04/15 17:12:08 GMT +08:00","wifiMac":"redacted","innerIp":"192.168.2.53","server":"mqtt.meross.com","port":443,"userId":redacted},"time":{"timestamp":redacted,"timezone":"America/Toronto","timeRule":[redacted]},"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":1,"lmTime":0}],"triggerx":[{"channel":0,"id":"redacted","count":1}],"timerx":[],"garageDoor":[{"channel":0,"open":0,"lmTime":redacted}]}}}}
[5/26/2021, 10:29:58 PM] [Meross] Current state CLOSED
```

**Homebridge Config:**
Under platforms:
```
{
            "platform": "Meross",
            "name": "Meross",
            "devices": [
                {
                    "deviceUrl": "192.168.2.53",
                    "messageId": "redacted",
                    "sign": "redacted",
                    "channel": 0,
                    "timestamp": redacted,
                    "model": "MSG100",
                    "name": "Garage door",
                    "garageDoorOpeningTime": 10
                }
            ]
        },
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/15721264/119757148-88774880-be72-11eb-93bb-a74dacd4387c.png)
![image](https://user-images.githubusercontent.com/15721264/119757214-a47aea00-be72-11eb-8475-f4e1c32975e0.png)

**Environment:**

* **Node.js Version**: v14.17.0
* **NPM Version**: 6.14.13
* **Homebridge Version**: 1.3.4
* **Homebridge Meross Plugin Version**: v5.0.2
* **Homebridge Config UI X Plugin Version**: v4.41.1
* **Operating System**: Docker image in a Hyper V VM on Win 10

**Comment by Conanap** [comment]
No fix yet, but I'm not sure if this is a plug-in bug or apple home app bug.

**Comment by christiantschoerner** [comment]
"Fixed" it by removing `"garageDoorOpeningTime": 10`. I don't know why but it works now.

**Comment by Conanap** [comment]
Thank you, seems to have fixed it initially. I'll leave this issue open for the author.

**Comment by Conanap** [comment]
I took a peak at the code; my sneaking suspicion is `this.lastSetTime` is incorrectly continuously updated somewhere, causing this part of the code to continuously assign `this.platform.Characteristic.CurrentDoorState.OPENING` to `this.CurrentDoorState`:
```

if (isOpen) {
        const currentTime = Math.floor(Date.now() / 1000);
        const elapsedTime = currentTime - this.lastSetTime;
        if (this.CurrentDoorState === this.platform.Characteristic.CurrentDoorState.OPENING) {
          this.CurrentDoorState =
            elapsedTime < this.device.garageDoorOpeningTime!
              ? this.platform.Characteristic.CurrentDoorState.OPENING
              : this.platform.Characteristic.CurrentDoorState.OPEN;
```

**Comment by Conanap** [comment]
Unfortunately the issue is back, even with the above temporary fix.

**Comment by Conanap** [comment]
I would like to reopen this issue if possible - it seems like if the garage was opening and someone interrupts with the physical button, the status gets stuck as opening. I would recommend a status check to see if it is closed every 15 seconds or something like that while opening to ensure no one has interrupted with the physical button.

**Comment by christiantschoerner** [comment]
> I would like to reopen this issue if possible - it seems like if the garage was opening and someone interrupts with the physical button, the status gets stuck as opening. I would recommend a status check to see if it is closed every 15 seconds or something like that while opening to ensure no one has interrupted with the physical button.

Can confirm the issue is still there. Removing `"garageDoorOpeningTime": 10` did not help long term.

**Comment by bwp91** [comment]
Once I get the garage door implementation working well (both local and cloud modes) then I will look into this :)

**Comment by bwp91** [comment]
This should be fixed in the newest beta (22).
I’ll copy what I wrote in the other issue thread:

when opened from homekit, if after the operation time the state is still opening then it will be updated to open

when closed from homekit, the plugin will mark as closing then wait for a “closed” notification from meross before marking as closed. due to security i think this is important. if after the operation time plus an extra 15 seconds the garage is still “closing” then the garage will then be marked as open again.

the cloud control statuses are in real time, and local polling is every 5 seconds (unless configured higher), so the garage should mark as closed when it, or just after, it has physically closed

Also to note, if the garage is controlled via meross app or a physical button, the plugin will no longer use opening/closed status, will simply mark as open or closed.

If anyone updates to the beta (v6) of the plugin and uses local connection modes, please review the changelog for configuration differences.

Thanks

**Comment by Conanap** [comment]
This sounds great, thanks. I'll verify the solution over the next few days and close the issue when I can verify it.

**Comment by bwp91** [comment]
Closing this issue as i'd like to keep conversation re MSG100 in a singular place in #302
thanks and hope the garage is working well! any issues please reply in other issue!
